# Common settings
common:
  structure_file: "/data01/genbiolab/mdanh/data/MD_scripts/test/new_ff/cnt_mem/ionized/cnt_mem_ionized/cnt_mem_ionized.psf"
  parameters_file: "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/par_all36m_prot.prm"
  parameters_files:
     - "/data01/genbiolab/mdanh/data/CHARMMFF/cnt_ff/final/cnt_oh.prm"
     - "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/par_all36m_prot.prm"
     - "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/par_all36_carb.prm"
     - "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/par_all36_lipid.prm"
     - "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/par_all36_na.prm"
     - "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/par_all36_cgenff.prm"
     - "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/toppar_water_ions_namd.str"

  temperature: 300
  cutoff: 12.0
  switch_dist: 10.0
  pairlist_dist: 14.0
  timestep: 2.0
  nonbonded_freq: 1
  full_elect_frequency: 2
  cell_basis_vector1: "81.54    0.0    0.0"
  cell_basis_vector2: "0.0   83.31   0.0"
  cell_basis_vector3: "0.0    0.0   80.0"
  cell_origin: "0.766   1.751  -0.858"
  pme_grid_spacing: 1.0
  pme_grid_size_x: 45
  pme_grid_size_y: 45
  pme_grid_size_z: 100
  langevin_damping_equilibration: 10
  langevin_damping_production: 1
  langevin_file: "langvin_water.pdb"
  langevin_col: "B"
  langevin_piston_target: 1.01325
  langevin_piston_period: 100.0
  langevin_piston_decay: 50.0
  first_timestep: 0
  use_flexible_cell: true
  use_constant_ratio: true
  use_constant_area: false

# Minimization stage config
minimization:
  stage: minimization
  job_description: "Minimization of CNT-membrane system"
  coordinates_file: "/data01/genbiolab/mdanh/data/MD_scripts/test/DPPC_CNT/ionized/cnt_mem_ionized/cnt_mem_ionized.pdb"
  output_name: "final_min"
  steps_per_cycle: 10
  restart_freq: 500
  dcd_freq: 200
  output_energies: 100
  output_pressure: 100
  num_minimize_steps: 30000

# Multi-stage equilibration configuration
equilibration_stages:
  num_stages: 6
  base_config:
    job_description: "Membrane equilibration with constraints"
    steps_per_cycle: 20
    restart_freq: 100000
    dcd_freq: 5000
    output_energies: 5000
    output_pressure: 5000
    num_steps: 50000
    timestep: 0.5
    langevin_damping: 10.0
    reassign_freq: 500
    reassign_temp: 300
  
  # Specific settings for each stage
  stage_specific:
    eq1:
      num_steps: 100000
      langevin_damping: 10.0
      timestep: 0.5 
      temperature: 300 

# Single equilibration stage config
equilibration:
  stage: equilibration
  job_description: "Single stage membrane equilibration"
  coordinates_file: "final_min.coor"
  extended_system_file: "final_min.xsc"
  output_name: "final_eq"
  steps_per_cycle: 20
  restart_freq: 500
  dcd_freq: 500
  output_energies: 500
  output_pressure: 500
  num_steps: 500000
  reassign_freq: 500
  reassign_temp: 300

# Production stage config
production:
  stage: production
  job_description: "NPT dynamics for membrane system"
  coordinates_file: "final_eq1.coor"
  extended_system_file: "final_eq1.xsc"
  velocities_file: "final_eq1.vel"
  output_name: "final_NPT"
  nonbonded_scaling: 0.833
  steps_per_cycle: 20
  restart_freq: 5000
  dcd_freq: 5000
  xst_freq: 5000
  output_energies: 5000
  output_pressure: 5000
  num_steps: 5000000

# Constraints configuration
constraints:
  enabled: true
  cons_pdb: "/data01/genbiolab/mdanh/data/MD_scripts/test/new_ff/cnt_mem/ionized/cnt_mem_ionized/cnt_constraints.pdb"
  cons_col: "B"
  cons_exp: 2

# CNT-specific restraints configuration (disabled - using constraints instead)
cnt_restraints:
  enabled: false
  cnt_ref_file: "/data01/genbiolab/mdanh/data/MD_scripts/working/restrains/check/restraints/cnt_restraint.ref"
  cnt_colvar_file: "/data01/genbiolab/mdanh/data/MD_scripts/working/restrains/check/restraints/cnt_only.colvar" 