# Common settings
common:
  structure_file: "/data01/genbiolab/mdanh/data/MD_pipeline/1BYI_ionized.psf"
  parameters_file: "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/par_all36m_prot.prm"
  # Uncomment and modify this to use multiple parameter files
  parameters_files:
     - "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/par_all36m_prot.prm"
     - "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/par_hbond.inp"
     - "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/par_all35_ethers.prm"
     - "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/par_all36_cgenff.prm"
     - "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/par_all36_lipid.prm"
     - "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/par_all36_na.prm"
     - "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/par_all36_carb.prm"
     - "/data01/genbiolab/mdanh/data/CHARMMFF/toppar/toppar_water_ions_namd.str"

  # Default temperature - can be overridden via command line for multiple temperature runs
  # Use --temperatures option to generate files for multiple temperatures
  # e.g., --temperatures 300 310 320
  temperature: 300
  cutoff: 12.0
  switch_dist: 10.0
  pairlist_dist: 14.0
  timestep: 2.0
  nonbonded_freq: 1
  full_elect_frequency: 2
  cell_basis_vector1: "85.0    0.0    0.0"
  cell_basis_vector2: "0.0   79.0    0.0"
  cell_basis_vector3: "0.0    0.0   90.0"
  cell_origin: "-17.604   -16.340  0.3"
  pme_grid_spacing: 1.0
  pme_grid_size_x: 45
  pme_grid_size_y: 45
  pme_grid_size_z: 100
  langevin_damping: 1
  langevin_piston_target: 1.01325
  langevin_piston_period: 100.0
  langevin_piston_decay: 50.0
  first_timestep: 0

# Minimization stage config
minimization:
  stage: minimization
  job_description: "Minimization of molecules"
  coordinates_file: "/data01/genbiolab/mdanh/data/MD_pipeline/1BYI_ionized.pdb"
  output_name: "final_min"
  steps_per_cycle: 10
  restart_freq: 500
  dcd_freq: 200
  output_energies: 100
  output_pressure: 100
  num_minimize_steps: 10000

# Equilibration stage config
equilibration:
  stage: equilibration
  job_description: "Equilibration of molecules"
  coordinates_file: "final_min.coor"
  extended_system_file: "final_min.xsc"
  output_name: "final_eq"
  steps_per_cycle: 20
  restart_freq: 100
  dcd_freq: 200
  output_energies: 100
  output_pressure: 100
  num_steps: 10000

# Production stage config
production:
  stage: production
  job_description: "NPT dynamics"
  coordinates_file: "final_eq.coor"
  extended_system_file: "final_eq.xsc"
  velocities_file: "final_eq.vel"
  output_name: "final_NPT"
  # Example of using multiple parameter files for this specific stage
  # Uncomment to use multiple parameter files only for production stage
  # parameters_files:
  #   - "../../common/par_all36_prot.prm"
  #   - "../../common/par_all36_lipid.prm"
  #   - "../../common/par_all36_cgenff.prm"
  nonbonded_scaling: 0.833
  steps_per_cycle: 20
  restart_freq: 10000
  dcd_freq: 5000
  xst_freq: 5000
  output_energies: 5000
  output_pressure: 5000
  num_steps: 500000 